version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish
artifacts:
  files:
  - TodoWebApp/build_output/**/*
  - scripts/**/*
