version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o TodoWebApp/build_output TodoWebApp/WebApp/WebApp.csproj
artifacts:
  files:
  - TodoWebApp/build_output/**/*
  - scripts/**/*
